# Generated by Django 6.0.3 on 2026-03-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_code_expires_at',
        ),
    ]
