# Generated by Django 6.0.3 on 2026-03-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workerskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerskill',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'Usta xizmati', 'verbose_name_plural': 'Usta xizmatlari'},
        ),
    ]
