# Generated by Django 6.0.3 on 2026-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
