# Generated by Django 6.0.3 on 2026-03-22 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_instagram_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_name', models.CharField(blank=True, max_length=120)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_profile_views', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_profile_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usta profil ko`rishi',
                'verbose_name_plural': 'Usta profil ko`rishlari',
                'ordering': ('-viewed_at',),
                'indexes': [models.Index(fields=['worker', '-viewed_at'], name='accounts_wo_worker__342b4e_idx'), models.Index(fields=['worker', 'viewer', '-viewed_at'], name='accounts_wo_worker__800b68_idx')],
            },
        ),
    ]
