# Generated by Django 6.0.3 on 2026-05-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_workerprofileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
