# Generated by Django 6.0.3 on 2026-03-18 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('price_type', models.CharField(choices=[('negotiable', 'Kelishiladi'), ('fixed', 'Aniq narx')], default='negotiable', max_length=20)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Aniq narx rejimi uchun qiymat', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Yangi'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
