# Generated by Django 6.0.3 on 2026-03-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('withdrawn', 'Bekor qilingan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobs.joborder')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E`longa murojaat',
                'verbose_name_plural': 'E`longa murojaatlar',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'worker'), name='unique_worker_vacancy_proposal')],
            },
        ),
    ]
