# Generated by Django 6.0.3 on 2026-03-23 03:34

from django.conf import settings
from django.db import migrations, models


def split_threads_by_vacancy(apps, schema_editor):
    ChatThread = apps.get_model('chat', 'ChatThread')
    VacancyProposal = apps.get_model('proposals', 'VacancyProposal')

    rows = list(
        ChatThread.objects
        .order_by('id')
        .values('id', 'client_id', 'worker_id', 'vacancy_id', 'created_at', 'updated_at')
    )
    for row in rows:
        proposal_rows = list(
            VacancyProposal.objects
            .filter(chat_thread_id=row['id'])
            .order_by('created_at', 'id')
            .values('id', 'vacancy_id')
        )
        if not proposal_rows:
            continue

        base_vacancy_id = row['vacancy_id'] or proposal_rows[0]['vacancy_id']
        if row['vacancy_id'] != base_vacancy_id:
            ChatThread.objects.filter(id=row['id']).update(vacancy_id=base_vacancy_id)

        thread_by_vacancy = {base_vacancy_id: row['id']}
        for proposal in proposal_rows:
            vacancy_id = proposal['vacancy_id']
            if vacancy_id in thread_by_vacancy:
                continue

            new_thread = ChatThread.objects.create(
                client_id=row['client_id'],
                worker_id=row['worker_id'],
                vacancy_id=vacancy_id,
            )
            ChatThread.objects.filter(id=new_thread.id).update(
                created_at=row['created_at'],
                updated_at=row['updated_at'],
            )
            thread_by_vacancy[vacancy_id] = new_thread.id

        for proposal in proposal_rows:
            target_thread_id = thread_by_vacancy.get(proposal['vacancy_id'])
            if target_thread_id and target_thread_id != row['id']:
                VacancyProposal.objects.filter(id=proposal['id']).update(chat_thread_id=target_thread_id)


def dedupe_threads_by_triplet(apps, schema_editor):
    ChatThread = apps.get_model('chat', 'ChatThread')
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    VacancyProposal = apps.get_model('proposals', 'VacancyProposal')

    keep_by_triplet = {}
    rows = list(
        ChatThread.objects
        .order_by('client_id', 'worker_id', 'vacancy_id', '-updated_at', '-id')
        .values('id', 'client_id', 'worker_id', 'vacancy_id')
    )
    for row in rows:
        key = (row['client_id'], row['worker_id'], row['vacancy_id'])
        keep_id = keep_by_triplet.get(key)
        if keep_id is None:
            keep_by_triplet[key] = row['id']
            continue

        duplicate_id = row['id']
        VacancyProposal.objects.filter(chat_thread_id=duplicate_id).update(chat_thread_id=keep_id)
        ChatMessage.objects.filter(thread_id=duplicate_id).update(thread_id=keep_id)
        ChatThread.objects.filter(id=duplicate_id).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_attachment'),
        ('proposals', '0002_vacancyproposal_chat_thread'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatthread',
            name='unique_client_worker_chat_thread',
        ),
        migrations.RunPython(split_threads_by_vacancy, noop_reverse),
        migrations.RunPython(dedupe_threads_by_triplet, noop_reverse),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(fields=('client', 'worker', 'vacancy'), name='unique_client_worker_vacancy_chat_thread'),
        ),
    ]
